{% set name = "librobometry" %}
{% set version = "1.2.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/robotology/robometry/archive/refs/tags/v{{ version }}.tar.gz
    sha256: ba2abda759332c57026b033c14a8aa5874e101bc86dd858bded62ab17381eedb

build:
  number: 1
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - ninja
  host:
    - ycm-cmake-modules
    - libmatio-cpp
    - libboost-headers
    - nlohmann_json
    - yarp
  run_constrained:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]


test:
  commands:
    - test -f $PREFIX/include/robometry/BufferManager.h  # [unix]
    - test -f $PREFIX/lib/librobometry${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_INC%\\robometry\\BufferManager.h exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\robometry.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\robometry.dll exit 1  # [win]

about:
  home: https://github.com/robotology/robometry
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Telemetry library for logging data.

extra:
  recipe-maintainers:
    - traversaro
